### ISSUE TITLE
Error when compacting db

### ISSUE THREAD

**Issue by scrombie** [wardle/hermes#58]
Hi great work on this. Ran into an issue when trying to compact the db on the latest release, it keeps throwing this error:

```
PS C:\Users\XXXX\Documents\dev\hermes> java -jar .\hermes-1.4.1265.jar --db .\raw\snomed.db\ compact
2023-09-15 17:12:15,427 [main] INFO  com.eldrix.hermes.core - Compacting database at  ".\\raw\\snomed.db\\" ...
2023-09-15 17:12:15,630 [main] ERROR com.eldrix.hermes.cmd.core - Uncaught exception on "main"
org.lmdbjava.Env$InvalidCopyDestination: Path must not exist for MDB_NOSUBDIR
        at org.lmdbjava.Env.validatePath(Env.java:448)
        at org.lmdbjava.Env.copy(Env.java:160)
        at com.eldrix.hermes.impl.lmdb$compact.invokeStatic(lmdb.clj:131)
        at com.eldrix.hermes.core$compact$fn__15563.invoke(core.clj:1331)
        at com.eldrix.hermes.core$compact.invokeStatic(core.clj:1331)
        at com.eldrix.hermes.cmd.core$compact.invokeStatic(core.clj:69)
        at com.eldrix.hermes.cmd.core$compact.invoke(core.clj:69)
        at com.eldrix.hermes.cmd.core$invoke_command.invokeStatic(core.clj:132)
        at com.eldrix.hermes.cmd.core$_main.invokeStatic(core.clj:160)
        at com.eldrix.hermes.cmd.core$_main.doInvoke(core.clj:141)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at com.eldrix.hermes.cmd.core.main(Unknown Source)
```

Indexing works fine. Starting the server also runs successfully. It's just the compact that throws the error.

Running on a Windows 11 x64 Machine

Any idea what could be causing this?

**Comment by wardle** [comment]
Thanks for this. Compaction basically makes a copy of the database and then deletes the old one, and then renames the new one. The error implies that the path at which the copy will be made already exists. Was compaction aborted first time around? Hermes should probably check if the destination path exists and delete first. Can you print the results of `dir raw/snomed.db`?

**Comment by scrombie** [comment]
I ran index and compact the first time and it failed. Then tried index alone and that worked, but compact kept on failing.

Result of dir raw\snomed.db
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         9/14/2023   2:05 PM                members.db
d-----         9/14/2023   2:04 PM                search.db
d-----         9/13/2023   2:16 PM                store.db
-a----         9/13/2023   1:58 PM            123 manifest.edn
```

Result of dir raw\snomed.db\store.db
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/13/2023   1:58 PM     5368709120 core.db
-a----         9/13/2023   1:58 PM           8192 core.db-lock
-a----         9/13/2023   2:16 PM     1126907904 core2.db
-a----         9/13/2023   1:58 PM     5368709120 refsets.db
-a----         9/13/2023   1:58 PM           8192 refsets.db-lock
-a----         9/13/2023   2:16 PM      730316800 refsets2.db
```

**Comment by wardle** [comment]
Yes. The intermediate files are in the way. I've just added a commit that will automatically delete any leftover files before attempting compaction. You can checkout the source code and use HEAD directly to check this, if you want, or simply delete the files core2.db and refsets2.db from that directory and try again.

**Comment by wardle** [comment]
Also see [v1.4.1275](https://github.com/wardle/hermes/releases/tag/v1.4.1275)

**Comment by scrombie** [comment]
Got it. Thanks a lot.

I deleted the files as advised. And that cleared the error, but it seems like it now hit a permission block. Looks like a windows issue:

```
2023-09-15 17:53:46,922 [main] INFO  com.eldrix.hermes.core - Compacting database at  ".\\raw\\snomed.db\\" ...
2023-09-15 17:54:07,322 [main] ERROR com.eldrix.hermes.cmd.core - Uncaught exception on "main"
java.nio.file.AccessDeniedException: .\raw\snomed.db\store.db\core2.db -> .\raw\snomed.db\store.db\core.db
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:328)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
        at java.base/java.nio.file.Files.move(Files.java:1429)
        at com.eldrix.hermes.impl.lmdb$compact.invokeStatic(lmdb.clj:133)
        at com.eldrix.hermes.core$compact$fn__15563.invoke(core.clj:1331)
        at com.eldrix.hermes.core$compact.invokeStatic(core.clj:1331)
        at com.eldrix.hermes.cmd.core$compact.invokeStatic(core.clj:69)
        at com.eldrix.hermes.cmd.core$compact.invoke(core.clj:69)
        at com.eldrix.hermes.cmd.core$invoke_command.invokeStatic(core.clj:132)
        at com.eldrix.hermes.cmd.core$_main.invokeStatic(core.clj:160)
        at com.eldrix.hermes.cmd.core$_main.doInvoke(core.clj:141)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at com.eldrix.hermes.cmd.core.main(Unknown Source)
PS C:\Users\XXXX\Documents\dev\hermes>
```
I think this was the issue that led to the compact terminating early in the first place

**Comment by wardle** [comment]
How weird. I probably should add a Windows host into the CI test pipeline, as I don't routinely develop, test or run on Windows. Can you double check you are not running out of disk space? I'm simply using `java.nio.file.Files/move` with options REPLACE_EXISTING, so this should work. What version of Java are you using?

While compaction is optional, this error definitely should not occur so I'd like to fix this. 

What are the results of `dir raw/snomed.db/store.db` after this error was thrown? 

Mark

**Comment by scrombie** [comment]
Here's what it looks like now:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/13/2023   1:58 PM     5368709120 core.db
-a----         9/13/2023   1:58 PM           8192 core.db-lock
-a----         9/15/2023   5:54 PM     1126907904 core2.db
-a----         9/13/2023   1:58 PM     5368709120 refsets.db
-a----         9/13/2023   1:58 PM           8192 refsets.db-lock
-a----         9/15/2023   5:54 PM      730316800 refsets2.db
```
It's definitely not a space issue, cause I still have over 300GB free on the drive I'm using for this. But I want to try a fresh start to see if the issue happens again. I'm currently redownloading the datafiles so I can retry again.

**Comment by wardle** [comment]
Do you have another process using this at the same time as running compaction? e.g. a server running? That would lock the datafiles and prevent deletion.

**Comment by wardle** [comment]
If you do not have another process running, then I can see where the issue might be and why it may only affect Windows. The store is opened at the beginning of the compact process but isn't closed until after compaction, potentially stopping a datafile from being deleted on Windows. Other OSs don't lock files in the same way.

**Comment by scrombie** [comment]
Still ran into the same permission issue even with the new download.

And No, no other processes (that I'm aware of are currently being run). I shut down the server running locally already before I raised the issue.
Could it be that the data files being downloaded are locked somehow, and can't be copied or processed afterwards?
I'm not sure how the download process works in the background, that could be worth checking out.
Happy to help however I can.

**Comment by wardle** [comment]
No it's a simple fix. The store is opened by Hermes. On other operating systems, they don't mind if you delete the files while opened, but Windows doesn't like it at all. I can simply close the store after the copy but before the new files are moved to replace the old files.

**Comment by wardle** [comment]
New release: https://github.com/wardle/hermes/releases/tag/v1.4.1278

**Comment by scrombie** [comment]
Awesome! Ran it with the new release and it works perfectly!

Thanks a lot for the help!

Again, really great work you're doing here. 🏆

**Comment by wardle** [comment]
Thanks. Stars and public endorsements always welcome! 😉
