### ISSUE TITLE
Error during import - IndexOutOfBoundsException, "length of pattern values not equal"

### ISSUE THREAD

**Issue by mitochon** [wardle/hermes#69]
Hi, thanks for making this tool available.

I tried running the import process against our dataset and it failed in a few places, e.g.

- When `mapTarget` is not specified in a [simple map reference set]( https://confluence.ihtsdotools.org/display/DOCRELFMT/5.2.3.1+Simple+Map+from+SNOMED+CT+Reference+Set)
```
clojure.lang.ExceptionInfo: length of pattern values not equal
	at com.eldrix.hermes.snomed$parse_fields.invokeStatic(snomed.clj:530)
	at com.eldrix.hermes.snomed$parse_simple_refset_item.invokeStatic(snomed.clj:546)
	at com.eldrix.hermes.snomed$parse_simple_refset_item.invoke(snomed.clj:539)
	at com.eldrix.hermes.snomed$parse_snomed_filename$fn__11445.invoke(snomed.clj:927)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
```
- When `guideURL` is not specified in a [MRCM domain reference set](https://confluence.ihtsdotools.org/display/DOCRELFMT/5.2.4.4+MRCM+Domain+Reference+Set)
```
java.lang.IndexOutOfBoundsException: null
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
	at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
	at clojure.lang.APersistentVector.invoke(APersistentVector.java:296)
	at com.eldrix.hermes.snomed$parse_mrcm_domain_refset_item.invokeStatic(snomed.clj:723)
	at com.eldrix.hermes.snomed$parse_mrcm_domain_refset_item.invoke(snomed.clj:709)
	at com.eldrix.hermes.snomed$parse_snomed_filename$fn__11445.invoke(snomed.clj:927)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
```

New to SNOMED-CT and RF2 files, but from what I understand these columns are optional.

I was able to run the import + index after removing entries that do not have these fields specified.

I'm currently using the provided jar from [v1.2.1208](https://github.com/wardle/hermes/releases/tag/v1.2.1208) because I'm currently on Java 11. If I try using the jar file from the latest tagged version it gave me a class loader error (java.lang.NoClassDefFoundError: java/util/SequencedCollection) - may I know what's the minimum Java version for the latest tag?

It could be I'm doing something wrong on my side, but let me know if I can provide additional information.
Thank you.

**Comment by wardle** [comment]
Would you mind sending minimal example files that reproduce this error - whatever the case, it would be better to have more informative error messages!

**Comment by wardle** [comment]
Release v1.4.1425 released with JDK11 compatibility.

**Comment by mitochon** [comment]
Thank you for the replies!
The new version v1.4.1425 works with Java 11.
I'll try to create a minimal example files and get back to you.
This is coming from our own data source.

**Comment by mitochon** [comment]
Steps to create a minimal set outlined below

```
#  create test directory structure, add test file

$ mkdir -p minimal/Snapshot/Refset/Map/
$ cat > minimal/Snapshot/Refset/Map/der2_ssRefset_SimpleMapWithDescriptionSnapshot_12345_20241021.txt
id	effectiveTime	active	moduleId	refsetId	referencedComponentId	mapTarget	mapTargetDescription
000d91ce-aae4-4f9e-ad06-51be576becd6	20241021	1	195941000112101	22671000001102	1434181000001106	ABC01256Q	
00280f1a-4c71-4683-8cb4-3e19e97ff9d9	20241021	1	195941000112101	22671000001102	1291061000001109	ABC08795Q	
```

Reproduce error. Double check the above formatting is preserved (tab-separated, with trailing tab at the end of the line).

```
$ java -jar hermes-1.4.1425.jar --db test.db import ~/snomed-test/minimal
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
2024-11-15 12:45:47,958 [async-thread-macro-13] INFO  com.eldrix.hermes.importer - Processing:  "der2_ssRefset_SimpleMapWithDescriptionSnapshot_12345_20241021.txt"  type:  "SimpleMapRefset"
2024-11-15 12:45:47,966 [main] ERROR com.eldrix.hermes.cmd.core - Uncaught exception on "main"
clojure.lang.ExceptionInfo: length of pattern values not equal
	at com.eldrix.hermes.snomed$parse_fields.invokeStatic(snomed.clj:524)
	at com.eldrix.hermes.snomed$parse_simple_map_refset_item.invokeStatic(snomed.clj:603)
	at com.eldrix.hermes.snomed$parse_simple_map_refset_item.invoke(snomed.clj:595)
	at com.eldrix.hermes.snomed$parse_snomed_filename$fn__11467.invoke(snomed.clj:921)
	at clojure.core$map$fn__5954.invoke(core.clj:2772)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3141)
	at clojure.core$doall.invokeStatic(core.clj:3156)
```

If last column is populated the import runs fine, e.g. overwrite the test file and re-run the import.

```
$ cat > minimal/Snapshot/Refset/Map/der2_ssRefset_SimpleMapWithDescriptionSnapshot_12345_20241021.txt
id	effectiveTime	active	moduleId	refsetId	referencedComponentId	mapTarget	mapTargetDescription
000d91ce-aae4-4f9e-ad06-51be576becd6	20241021	1	195941000112101	22671000001102	1434181000001106	ABC01256Q	AB
00280f1a-4c71-4683-8cb4-3e19e97ff9d9	20241021	1	195941000112101	22671000001102	1291061000001109	ABC08795Q	AB
```

**Comment by wardle** [comment]
Thanks for this that is very helpful. I had a quick look at this and here are my reflections so far.

- The likely issue is this [line of code](https://github.com/wardle/hermes/blob/bcc0df1bb06b0f86054681ca2630c256f8ba65fd/src/com/eldrix/hermes/importer.clj#L106) - in which a crude string split occurs.
- This crude string split fails to return a nil or empty string if the line ends with two tab characters `\t\t`
- The filename provides a pattern to define the content of the fields in a reference set - see [this code](https://github.com/wardle/hermes/blob/bcc0df1bb06b0f86054681ca2630c256f8ba65fd/src/com/eldrix/hermes/snomed.clj#L511) - this has a crude check to ensure that the pattern matches the content parsed. e.g. ssRefset would have two string fields.

A simple experiment at the REPL demonstrates the issue with the crude string split:
```
(str/split "one\ttwo\tthree\t\t\r\n" #"\t")
=> ["one" "two" "three" "" "\r\n"]
(str/split "one\ttwo\tthree\t\t\n" #"\t")
=> ["one" "two" "three" "" "\n"]
(str/split "one\ttwo\tthree\t\t" #"\t")
=> ["one" "two" "three"]
```
Evidently the string split works, but the code uses `line-seq` to return a sequence of lines as strings, removing any line terminators such as `\n` or `\r`. As such, a trailing empty field is omitted.

The fix is likely to be straightforward therefore, and simply require a more tolerant tab-separated parser than `str/split`.

**Comment by wardle** [comment]
HEAD now includes a fix to the TSV file import that copes with missing values in the end column. If you run from source using the Clojure command line tool (ie clj -M:run), then would you like to test this with your custom complex map reference set?
